# Generated by Django 5.0.4 on 2024-05-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='модель')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выхода продукта на рынок')),
                ('network_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkunit', verbose_name='Объект сети')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
